### PR TITLE
Cleanups, updates, and bug-fixes

### PR DESCRIPTION
**Pull request by Sailsman63**
See discussion at https://sourceforge.net/p/aoi/discussion/47783/thread/35c7ff78dd/?limit=25&page=3#d8ba for details.

### CODE REVIEW

**Comment by peteihis** [comment]
Could you upload .jar file? It would make testing somewhat easier/faster.

**Comment by Sailsman63** [comment]
Sure, here you go! Note: I have not yet updated the Extensions.xml, so no way to easily tell it apart from the current repo version.

I would also like feedback on the build scripts, if at all possible. It's a standard gradle build, so basic gradle commands will work. Not sure if we want to migrate all of the project to it, but this makes a nice little test-bed. (Stuff like automatically pulling in dependencies is easier in gradle than ant, but I'm not sure if I like how... unreadable the files are)
[stlTranslator.zip](https://github.com/ArtOfIllusion/STLTranslator/files/7647375/stlTranslator.zip)

**Comment by peteihis** [comment]
So **GRADLE**:

I set Gradle up on my still pretty empty laptop and ran a build. Well... it did the job, but...

- I downloaded the STL-Transaltor PR, which came in as 'STLTranslator-normal-compare'. I put the directory under Art Of Illusion root. (No build directories on the laptop at the moment), changed the AoI-path to `..\ArtofIllusion.jar` wrote a bat-file to get any system outputs saved....
- It reported `BUILD SUCCESSFUL in 10s`, but there was no STL-Translator in Art Of Illusion\Plugins. Instead there was a 'STLTranslator-normal-compare.jar' in Art Of Illusion\STLTranslator-normal-compare\Plugins.
- The build directory has very deep structures with a lot of empty sub-directories.
- And Gradle also wrote a couple of information files in AoI-root.

Honestly I can not seriously make a vote between Ant and Gradle but at least Gradle seems to need more precice instructions to work as expected as in where to write the ready .jar and what to call it.

As a matter of fact I, just a couple of months back, got myself educated enough on Ant that I was able to create builds of my own and while lerning that I discovered that there seemed to be something a little bit off with the AoI-build variables, like what is `packageName` and what is `appName`. I don't remember exactly, but at least those did not seem to be properly separated and/or they were somehow cross-used.

And then **STL-Translator**:

Not much to say at the moment but that I had a closer look at how the centering is done. 

- The ascii import does not separate the Light 1 and Camera 1 from the imported objects, so it really does move everythig. Camera 1 and Light 1 are added to the scene when it is created, so they are already there at this point. The Camera was not affected because I had checked Frame on and that naturally repositioned it.
- The centering code itself is... Just weird. And built entirely wrong. As the space can be divided to 8 coordinate octants this contraption would fail 15 times out of 16. It would move things a bit in probably half of the possible cases but getting the imported group correctly centered would be a rarity.
- I'd suggest to remove that function now. A far more simple one can be build just out of BoundingBox and Vec3 (no need to declare dx, dy .... or minX, maxX. And there should not be any need to have it in two places either, it should be in a separate method that is called after a successful import. I'd be happy to provide that.

**Comment by Sailsman63** [comment]
Notes on gradle experience so far:

- The plugin source structure is *not* intended to be placed under the Art Of Illusion root. Instead, it would (usually) be a sibling: (The same is true of the (updated) ant-based builds)
- The build script is not supposed to deploy the plugin directly to the ArtOfIllusion Plugins directory. I might consider adding that as a separate target, but the basic build should keep the plugin jar local.
- The odd name you got was due to the directory name you ended up with (Consequence of unzipping just a single branch. Normal `git clone`s of the repo will be in a directory called `STLTranslator`
- `build` directory *is* weird, but it's all used internally by gradle. We should never have to dig through it under normal circumstances.

The directory structure ends up looking like this:
- ./MyDevelopmentDirectory/
    - ArtOfIlusion/    -Optional. If you don't have a dev build, just modify gradle.properties to point at your installed ArtOfIllusion.jar
        - Plugins/
        - &tc./
    - STLTranslator/
        - build/          -We ignore this. Gradle uses it for interim stuff.
        - Plugins/      -This is where the plugin jar(s) go. Name based on the parent directory.
    - AnotherPlugin/

**Comment by Sailsman63** [comment]
> The ascii import does not separate the Light 1 and Camera 1 from the imported objects, so it really does move everythig. 

Easy fix. Just pushed an update.

> The centering code itself is... Just weird. And built entirely wrong. As the space can be divided to 8 coordinate octants this contraption would fail 15 times out of 16. 

This I don't see. Do you have an example file that fails?

**Comment by peteihis** [comment]
> This I don't see. 

Don't see in the code or by examples?

In the code:

~~~Java
// Creates a zero sized BoundixBox in the origin

vert = new Vec3();
BoundingBox bounds = new BoundingBox(vert, vert);

// Extends the box coordinates, mins only toward negative and maxes toward positive
// If the object is in all positive (> 0.0) coordinates, one end of the box will still be at 0.0
// and consequently the center will not be where the middle of the object is.

if (vert.x < bounds.minx) bounds.minx = vert.x;
if (vert.x > bounds.maxx) bounds.maxx = vert.x;
...

// Calculates into the move vector only the difference from positive to zero.
// If the center is in negative numbers centering will not happen.

double dx = (centre.x > 0.0 ? -centre.x : 0.0);
...

~~~~

The only case where centering is done correctly is when the *actual* object bounds cover the scene origin and the center of box is in the all positive octant. If the entire object is in positive coordinates, the centering will happen a kind of half way. If it is all negative no centering will take place at all.

If you test by AoI alone, this won't come up because this exporter forces the objects to the all protive octant. Most others I have used don't. (Just found one that does. The first one in my career, I believe.)

Considering the history of this code it probably is nothing to wonder but there is some over thinking here. Basically it is not a good idea to process the data while you are importing it. It is simpler afterwards. I'd suggest just import (ascii or binary) into the new scene as they are and after that phase: 
- Get copy of the bounding box of the first imported object
- Outset and transform with the rest
- Minus that center vector from the position coordinates of the objects. 

The object bounding boxes already to all the work for you, no need to hunt maxes and mins. :)

Attached three pieces, one of which will be centered and the rest not.

[Test pieces.zip](https://github.com/ArtOfIllusion/STLTranslator/files/7673276/Test.pieces.zip)

**Comment by Sailsman63** [comment]
Ahh... Now I see it. Your proposed solution is probably also the way to go, but see below.

> there is some over thinking here. Basically it is not a good idea to process the data while you are importing it. It is simpler afterwards. 

True, but that's moving even more into a deeper refactoring. I've got a list of things that I think *could* be done with this code:
- Whitespace/indent cleanup
- Break the Importer and Exporter out into separate files
- Maybe re-write the ASCII parser entirely? I find it very unreadable....
- Remove references to ModelingApp
- ???

The thing is, I've already made much more extensive changes than I originally intended to for this particular go-round. I'd like to push other pre-existing issues off to be addressed separately. Would you be willing to open an issue for this one?

For the moment: do any of the changes proposed here introduce new issues, or have troubles with their implementation?

**Comment by peteihis** [comment]
>Would you be willing to open an issue for this one?

Sure, why not. My plan, stage #1 would be:
- White space & al.
- Fix he centering
- Make the all-positive export optional
- Line-up the UI elements
- Maybe attend the ModelligApp references

The rest I'd leave for later.

>  do any of the changes proposed here introduce new issues

Not that I'm aware of. At least nothig came up in testing when you sent the development versions.

**Pull request merged**
